# Generated by Django 4.1.7 on 2023-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='can_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
    ]
