# Generated by Django 4.1.7 on 2023-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_topic_updated_at_topic_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='Жопа', max_length=10),
            preserve_default=False,
        ),
    ]
