# Generated by Django 4.1.7 on 2023-03-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
