# Generated by Django 4.1.7 on 2023-03-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment'),
        ),
    ]
