# Generated by Django 4.1.7 on 2023-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_topic_forum_topic_categor_e92d61_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='forum_topic_categor_1b5df2_idx',
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category', 'tag', 'user'], name='forum_topic_categor_1a9ccf_idx'),
        ),
    ]
