# Generated by Django 4.1.7 on 2023-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_comment_forum_comme_created_7f9d8d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at'], name='forum_topic_created_825539_idx'),
        ),
    ]
