# Generated by Django 4.1.7 on 2023-03-13 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0020_topic_forum_topic_created_825539_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='forum_topic_created_825539_idx',
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-created_at'], name='forum_topic_created_60d8a9_idx'),
        ),
    ]
